{{- if .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" $ }}-secret 
type: Opaque
data:
{{- range $key, $val := .Values.secret }}
{{ $key | indent 2}}: {{ $val | b64enc | quote }}
{{- end }}
{{- end }}